# This is a sample build configuration for deploying to HEROKU.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Dockerhub as your build environment.
# image: java:8
#
# This script depends on two environment variables to be set in Bitbucket Pipelines
# 1. $HEROKU_API_KEY - https://devcenter.heroku.com/articles/platform-api-quickstart
# 2. $HEROKU_APP_NAME - Your app name in Heroku

pipelines:
  default:
    - step:
        name: Create artifact
        script:
          - tar czfv application.tgz dist/
        artifacts:
          - application.tgz
    - step:
       script: # Modify the commands below to build your repository.
         - pipe: atlassian/heroku-deploy:1.1.1
           variables:
             HEROKU_API_KEY:  $HEROKU_API_KEY
             HEROKU_APP_NAME: $HEROKU_APP_NAME
             ZIP_FILE: 'application.tgz'
             # WAIT: '<boolean>' # Optional.
             # DEBUG: '<boolean>' # Optional